/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcessingRouteRouteImport } from './routes/processing/route'
import { Route as LoadRouteRouteImport } from './routes/load/route'
import { Route as IndexRouteImport } from './routes/index'

const ProcessingRouteRoute = ProcessingRouteRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadRouteRoute = LoadRouteRouteImport.update({
  id: '/load',
  path: '/load',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/load': typeof LoadRouteRoute
  '/processing': typeof ProcessingRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/load': typeof LoadRouteRoute
  '/processing': typeof ProcessingRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/load': typeof LoadRouteRoute
  '/processing': typeof ProcessingRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/load' | '/processing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/load' | '/processing'
  id: '__root__' | '/' | '/load' | '/processing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoadRouteRoute: typeof LoadRouteRoute
  ProcessingRouteRoute: typeof ProcessingRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load': {
      id: '/load'
      path: '/load'
      fullPath: '/load'
      preLoaderRoute: typeof LoadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoadRouteRoute: LoadRouteRoute,
  ProcessingRouteRoute: ProcessingRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
